### ISSUE TITLE
Migrate UIKit iOS and Android Java Kotlin Tasks app from old docs

### ISSUE THREAD

**Issue by mbalex99** [getditto/docs#14]
# Problem

We need to migrate the old ToDo list app from the old docs to here:

# Solution

Move all the markdown and images over
However understand that we've made some changes across all the apps:

- [ ] "ToDo" or "To Do" is now "Tasks"
- [ ] `document.text` is `document.body`
- [ ] `document.isComplete` is `document.isCompleted`
- [ ] Remove the `dateCreated` property, this was never that useful. 
- [ ] Split the documentation into 4 pages similar to the SwiftUI or JetPack compose tutorial instead of it all being on one page. 
- [ ] Can you also help update: https://github.com/getditto/samples/tree/master/tasks/ for iOS and Android?

**Comment by kndoshn** [comment]
## iOS
- [x] "ToDo" or "To Do" is now "Tasks"
- [x] `document.text` is `document.body`
- [x] `document.isComplete` is `document.isCompleted`
- [x] Remove the `dateCreated` property, this was never that useful. 
- [x] Split the documentation into 4 pages similar to the SwiftUI or JetPack compose tutorial instead of it all being on one page. 
- [x] Can you also help update: https://github.com/getditto/samples/tree/master/tasks/ for iOS and Android?

## Android
- [ ] "ToDo" or "To Do" is now "Tasks"
- [ ] `document.text` is `document.body`
- [ ] `document.isComplete` is `document.isCompleted`
- [ ] Remove the `dateCreated` property, this was never that useful. 
- [ ] Split the documentation into 4 pages similar to the SwiftUI or JetPack compose tutorial instead of it all being on one page. 
- [ ] Can you also help update: https://github.com/getditto/samples/tree/master/tasks/ for iOS and Android?
