### ISSUE TITLE
Problem: Android Check Permissions Code is not up to date

### ISSUE THREAD

**Issue by mbalex99** [getditto/docs#146]
# Problem

See: https://docs.ditto.live/installation/android

- [x] The check permissions code is not correct 
- [x] Please specify what `requireActivity()` is, that code doesn't exist anywhere
- [x] Add both the kotlin and java examples if you could
- [x] I think we need to add these permissions checks to the To Do list tutorials 
# Solution

This is what I've used in my Kotlin projects:

```
fun checkPermissions() {
        val missing = DittoSyncPermissions(this).missingPermissions()
        if (missing.isNotEmpty()) {
            this.requestPermissions(missing, 0)
        }
    }
 ```

**Comment by okdistribute** [comment]
I don't know much about Kotlin, and before I take it out I'm just trying to understand why it's there. In our cars app, we use `requireActivity()`, so that's probably where this came from.

I briefly looked into the android documentation and it seems like `requiredActivity()` is a part of the [Fragment](https://developer.android.com/reference/kotlin/androidx/fragment/app/Fragment#requireActivity()) and `this` can only be used while inside of the activity, so it is less extensible and generalizable to modular/complex apps. Are kotlin developers knowledgable about what `requireActivity()` is? It was introduced in 27.0.1 (2018).

**Comment by phatblat** [comment]
On android the code behind a "screen" is either an Activity or a Fragment+Activity. Fragment is somewhat newer and provides for more reusable UI, but in some cases you may need to tap into the greater power of an Activity from a Fragment. I'm guessing that's what this `requireActivity()` is for. I'm not sure why we have `requireActivity()` in this code sample twice.

Really, all we need inside `DittoSyncPermissions` is a Context.

> You can get the context by invoking getApplicationContext(), getContext(), getBaseContext() or this (when in a class that extends from Context, such as the Application, Activity, Service and IntentService classes).

A Fragment _may_ have a Context, but `getContext()` is nullable. I believe `requireActivity()` is a way to force the code to only work on a Fragment that has a Context.
