### ISSUE TITLE
Supported Platforms missing C# and C++

### ISSUE THREAD

**Issue by bigfish24** [getditto/docs#275]
C++ may or may not support Qt mobile targets (and macOS) anymore but works Windows and Linux.

C# can run on all platforms but missing P2P transports on Windows?

https://docs.ditto.live/rust/common/supported-platforms

**Comment by bigfish24** [comment]
Can Java or Kotlin work outside of Android?

**Comment by okdistribute** [comment]
This information should be on the Installation page for each language.

We should also improve this page to use the Javascript Tabs table so that it's easier to visually navigate it

https://github.com/getditto/docs/blob/e63fbbf7bd6967c82aaa30d83e4dd85dffa739a3/docs/ios/installation.mdx?plain=1#L11-L19

<img width="861" alt="Screen Shot 2022-08-03 at 8 50 46 PM" src="https://user-images.githubusercontent.com/633012/182759188-11d9f756-64d3-439f-84cd-81fec97b392d.png">

**Comment by phatblat** [comment]
FYI, BLE is coming to Windows and Linux soon #6371

**Comment by okdistribute** [comment]
Yay
